[2025-01-30T11:16:24.079+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T11:16:24.097+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clean_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-30T11:16:24.108+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clean_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-30T11:16:24.110+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T11:16:24.132+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2023-01-01 00:00:00+00:00
[2025-01-30T11:16:24.148+0000] {standard_task_runner.py:72} INFO - Started process 79 to run task
[2025-01-30T11:16:24.153+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'clean_churn_dataset', 'extract', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/clean_churn.py', '--cfg-path', '/tmp/tmpt1ivpr48']
[2025-01-30T11:16:24.157+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask extract
[2025-01-30T11:16:24.214+0000] {task_command.py:467} INFO - Running <TaskInstance: clean_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [running]> on host 39e517c587d1
[2025-01-30T11:16:24.297+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clean_churn_dataset' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2025-01-30T11:16:24.299+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T11:16:24.300+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T11:16:24.301+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-01-30 11:16:24.099058+00:00
[2025-01-30T11:16:24.301+0000] {logging_mixin.py:190} INFO - Dag name:clean_churn_dataset and current dag run status:running
[2025-01-30T11:16:24.302+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T11:16:24.315+0000] {base.py:84} INFO - Retrieving connection 'destination_db'
[2025-01-30T11:16:24.316+0000] {sql.py:186} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-***-providers-mysql<5.7.1
* apache-***-providers-elasticsearch<5.5.1
* apache-***-providers-postgres<5.13.0
[2025-01-30T11:16:24.509+0000] {warnings.py:109} WARNING - /opt/***/dags/clean_churn.py:69: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql, conn).drop(columns=['id'])

[2025-01-30T11:16:24.576+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/clean_churn.py", line 69, in extract
    data = pd.read_sql(sql, conn).drop(columns=['id'])
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 5399, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 4505, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 4546, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6934, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['id'] not found in axis"
[2025-01-30T11:16:24.595+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-30T11:16:24.596+0000] {logging_mixin.py:190} INFO - Task start:2025-01-30 11:16:24.099058+00:00 end:2025-01-30 11:16:24.595198+00:00 duration:0.49614
[2025-01-30T11:16:24.598+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): extract> dag:<DAG: clean_churn_dataset> dagrun:<DagRun clean_churn_dataset @ 2023-01-01 00:00:00+00:00: scheduled__2023-01-01T00:00:00+00:00, state:running, queued_at: 2025-01-30 11:16:22.204039+00:00. externally triggered: False>
[2025-01-30T11:16:24.598+0000] {logging_mixin.py:190} INFO - Failure caused by "['id'] not found in axis"
[2025-01-30T11:16:24.599+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=clean_churn_dataset, task_id=extract, run_id=scheduled__2023-01-01T00:00:00+00:00, execution_date=20230101T000000, start_date=20250130T111624, end_date=20250130T111624
[2025-01-30T11:16:24.613+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T11:16:24.615+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task extract ("['id'] not found in axis"; 79)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/clean_churn.py", line 69, in extract
    data = pd.read_sql(sql, conn).drop(columns=['id'])
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 5399, in drop
    return super().drop(
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 4505, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 4546, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6934, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['id'] not found in axis"
[2025-01-30T11:16:24.649+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-30T11:16:24.672+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T11:16:24.677+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
