[2025-01-18T19:28:50.383+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract manual__2025-01-18T19:28:46.745385+00:00 [queued]>
[2025-01-18T19:28:50.390+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract manual__2025-01-18T19:28:46.745385+00:00 [queued]>
[2025-01-18T19:28:50.391+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-18T19:28:50.402+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-01-18 19:28:46.745385+00:00
[2025-01-18T19:28:50.409+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2025-01-18T19:28:50.417+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'extract', 'manual__2025-01-18T19:28:46.745385+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmp_m_m6b63']
[2025-01-18T19:28:50.418+0000] {standard_task_runner.py:85} INFO - Job 221: Subtask extract
[2025-01-18T19:28:50.460+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.extract manual__2025-01-18T19:28:46.745385+00:00 [running]> on host 5dfc028d3dc8
[2025-01-18T19:28:50.529+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T19:28:46.745385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-18T19:28:46.745385+00:00'
[2025-01-18T19:28:50.531+0000] {churn.py:71} INFO - Извлечение данных из источника.
[2025-01-18T19:28:50.533+0000] {base.py:73} INFO - Using connection ID 'source_db' for task execution.
[2025-01-18T19:28:50.681+0000] {warnings.py:109} WARNING - /opt/***/dags/churn.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql, conn)

[2025-01-18T19:28:51.035+0000] {churn.py:88} INFO - Данные успешно извлечены.
[2025-01-18T19:28:51.036+0000] {python.py:194} INFO - Done. Returned value was:      customer_id  begin_date  ... dependents multiple_lines
0     7590-VHVEG  2020-01-01  ...         No           None
1     5575-GNVDE  2017-04-01  ...         No             No
2     3668-QPYBK  2019-10-01  ...         No             No
3     7795-CFOCW  2016-05-01  ...         No           None
4     9237-HQITU  2019-09-01  ...         No             No
...          ...         ...  ...        ...            ...
7038  6840-RESVB  2018-02-01  ...        Yes            Yes
7039  2234-XADUH  2014-02-01  ...        Yes            Yes
7040  4801-JZAZL  2019-03-01  ...        Yes           None
7041  8361-LTMKD  2019-07-01  ...         No            Yes
7042  3186-AJIEK  2014-08-01  ...         No             No

[7043 rows x 20 columns]
[2025-01-18T19:28:51.118+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py:373: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if _pandas_api.is_sparse(col):

[2025-01-18T19:28:51.242+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=extract, execution_date=20250118T192846, start_date=20250118T192850, end_date=20250118T192851
[2025-01-18T19:28:51.268+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-18T19:28:51.296+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
