[2025-01-13T20:04:05.074+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.load manual__2025-01-13T20:03:57.126636+00:00 [queued]>
[2025-01-13T20:04:05.081+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.load manual__2025-01-13T20:03:57.126636+00:00 [queued]>
[2025-01-13T20:04:05.081+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-13T20:04:05.093+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-01-13 20:03:57.126636+00:00
[2025-01-13T20:04:05.100+0000] {standard_task_runner.py:57} INFO - Started process 112 to run task
[2025-01-13T20:04:05.102+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'load', 'manual__2025-01-13T20:03:57.126636+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpjowr60wl']
[2025-01-13T20:04:05.104+0000] {standard_task_runner.py:85} INFO - Job 117: Subtask load
[2025-01-13T20:04:05.141+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.load manual__2025-01-13T20:03:57.126636+00:00 [running]> on host 093b74c9e550
[2025-01-13T20:04:05.284+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T20:03:57.126636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T20:03:57.126636+00:00'
[2025-01-13T20:04:05.383+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T20:04:05.384+0000] {base.py:73} INFO - Using connection ID 'destination_db' for task execution.
[2025-01-13T20:04:05.659+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/churn.py", line 164, in load
    hook.insert_rows(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 509, in insert_rows
    cur.execute(sql, values)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "monthly_charges"
LINE 1: ...date','type','paperless_billing','payment_method','monthly_c...
                                                             ^

[2025-01-13T20:04:05.670+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=prepare_churn_dataset, task_id=load, execution_date=20250113T200357, start_date=20250113T200405, end_date=20250113T200405
[2025-01-13T20:04:05.683+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 117 for task load (invalid input syntax for type double precision: "monthly_charges"
LINE 1: ...date','type','paperless_billing','payment_method','monthly_c...
                                                             ^
; 112)
[2025-01-13T20:04:05.717+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-13T20:04:05.732+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
