[2025-01-30T11:16:29.255+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T11:16:29.269+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clean_churn_dataset.create_table manual__2025-01-30T11:16:27.539754+00:00 [queued]>
[2025-01-30T11:16:29.276+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clean_churn_dataset.create_table manual__2025-01-30T11:16:27.539754+00:00 [queued]>
[2025-01-30T11:16:29.277+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T11:16:29.290+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): create_table> on 2025-01-30 11:16:27.539754+00:00
[2025-01-30T11:16:29.298+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-01-30T11:16:29.301+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'clean_churn_dataset', 'create_table', 'manual__2025-01-30T11:16:27.539754+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/clean_churn.py', '--cfg-path', '/tmp/tmp4970m_8b']
[2025-01-30T11:16:29.303+0000] {standard_task_runner.py:105} INFO - Job 93: Subtask create_table
[2025-01-30T11:16:29.350+0000] {task_command.py:467} INFO - Running <TaskInstance: clean_churn_dataset.create_table manual__2025-01-30T11:16:27.539754+00:00 [running]> on host 39e517c587d1
[2025-01-30T11:16:29.414+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='clean_churn_dataset' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T11:16:27.539754+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T11:16:27.539754+00:00'
[2025-01-30T11:16:29.416+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T11:16:29.417+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T11:16:29.417+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-30 11:16:29.270763+00:00
[2025-01-30T11:16:29.418+0000] {logging_mixin.py:190} INFO - Dag name:clean_churn_dataset and current dag run status:running
[2025-01-30T11:16:29.419+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T11:16:29.427+0000] {base.py:84} INFO - Retrieving connection 'destination_db'
[2025-01-30T11:16:29.428+0000] {sql.py:186} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-***-providers-mysql<5.7.1
* apache-***-providers-elasticsearch<5.5.1
* apache-***-providers-postgres<5.13.0
[2025-01-30T11:16:29.434+0000] {base.py:84} INFO - Retrieving connection 'destination_db'
[2025-01-30T11:16:29.887+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/clean_churn.py", line 51, in create_table
    logger.info("Создание таблицы clean_users_churn.")
NameError: name 'logger' is not defined
[2025-01-30T11:16:29.902+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-30T11:16:29.903+0000] {logging_mixin.py:190} INFO - Task start:2025-01-30 11:16:29.270763+00:00 end:2025-01-30 11:16:29.901892+00:00 duration:0.631129
[2025-01-30T11:16:29.904+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): create_table> dag:<DAG: clean_churn_dataset> dagrun:<DagRun clean_churn_dataset @ 2025-01-30 11:16:27.539754+00:00: manual__2025-01-30T11:16:27.539754+00:00, state:running, queued_at: 2025-01-30 11:16:27.567663+00:00. externally triggered: True>
[2025-01-30T11:16:29.904+0000] {logging_mixin.py:190} INFO - Failure caused by name 'logger' is not defined
[2025-01-30T11:16:29.905+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=clean_churn_dataset, task_id=create_table, run_id=manual__2025-01-30T11:16:27.539754+00:00, execution_date=20250130T111627, start_date=20250130T111629, end_date=20250130T111629
[2025-01-30T11:16:29.915+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T11:16:29.917+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 93 for task create_table (name 'logger' is not defined; 93)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/clean_churn.py", line 51, in create_table
    logger.info("Создание таблицы clean_users_churn.")
NameError: name 'logger' is not defined
[2025-01-30T11:16:29.958+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-30T11:16:29.978+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T11:16:29.982+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
